//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public int Discipline_Id { get; set; }
        public string Discipline_Name { get; set; }
        public Nullable<int> C_Professor_ID { get; set; }
    }
}
