//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professors
    {
        public int Professor_Id { get; set; }
        public string C_Professor_Name { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public Nullable<decimal> Salary { get; set; }
    }
}
