//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Student_Id { get; set; }
        public string Student_Name { get; set; }
        public Nullable<System.DateTime> Student_Date_of_Birth { get; set; }
        public string Student_ID_Number { get; set; }
    }
}
